name: hammer
environment: metaworld

task_name: &task_name assembly-v2

use_abs_action: &use_abs_action false
 

feedback_threshold: 0.1  # for abs, should be 0.05

dim_a: &dim_a 4
dim_o: &dim_o 35 # dim of observation for low-dim states

e: [0.2, 0.2, 0.2, 0.2]  # only define diagional 
loss_weight_inverse_e: [1.0, 1.0, 1.0, 1.0]

camera_names: ["robot0_eye_in_hand", 'agentview']

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: [3, 96, 96]
      type: rgb
    agent_pos:
      shape: [2]
      type: low_dim
  action:
    shape: [2]

crop_shape: [84, 84]

gripper_qpose_max: [ 0.04187732, -0.00039201]
gripper_qpose_min: [-0.00132913, -0.04164233]
robot0_eef_pos_max: [0.29555445, 0.31293629, 1.10113877]
robot0_eef_pos_min: [-0.33556048831637464, -0.04873956,  0.77917393]


number_of_repetitions: 50
evaluations_per_training: 10
max_num_of_episodes: 162
max_time_steps_episode: 300
max_time_steps_per_repetition: 700000
